DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'listen') THEN
        CREATE USER "listen" WITH PASSWORD '';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'listen_db') THEN
        EXECUTE 'CREATE DATABASE listen_db';
    END IF;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname = 'user_schema') THEN
        CREATE SCHEMA "user_schema";
    END IF;
END $$;

GRANT ALL PRIVILEGES ON DATABASE "listen_db" TO "listen";
GRANT ALL PRIVILEGES ON SCHEMA "user_schema" TO "listen";
ALTER SCHEMA "user_schema" OWNER TO "listen";

-- Create tables with the correct owner
CREATE TABLE IF NOT EXISTS "user_schema"."users" (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USERNAME TEXT,
    PASSWORD TEXT    
);
ALTER TABLE "user_schema"."users" OWNER TO "listen";

CREATE TABLE IF NOT EXISTS "user_schema"."patients" (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID BIGINT,
    CONSTRAINT fk_user
      FOREIGN KEY (USER_ID)
      REFERENCES "user_schema"."users" (ID)
      ON DELETE CASCADE,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    IEP_DATE TEXT,
    EVAL_DATE TEXT,
    SCHOOL TEXT,
    THERAPY_TYPE TEXT,
    TEACHER TEXT,
    ROOM_NUMBER TEXT,
    GRADE_LEVEL TEXT,
    DOB TEXT
);
ALTER TABLE "user_schema"."patients" OWNER TO "listen";

CREATE TABLE IF NOT EXISTS "user_schema"."tests" (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PATIENT_ID BIGINT,
    CONSTRAINT fk_patient
      FOREIGN KEY (PATIENT_ID)
      REFERENCES "user_schema"."patients" (ID)
      ON DELETE CASCADE,
    TEST_NAME TEXT,
    TEST_TYPE TEXT,
    TEST_DETAILS TEXT,
    TEST_DATE TEXT,
    TEST_DATA TEXT,
    TEST_AUDIO BYTEA,
    TEST_ANALYSIS TEXT
);
ALTER TABLE "user_schema"."tests" OWNER TO "listen";

-- Grant permissions on sequences
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA "user_schema" TO "listen";

-- Set ownership on sequences
ALTER SEQUENCE IF EXISTS "user_schema"."users_id_seq" OWNER TO "listen";
ALTER SEQUENCE IF EXISTS "user_schema"."patients_id_seq" OWNER TO "listen";
ALTER SEQUENCE IF EXISTS "user_schema"."tests_id_seq" OWNER TO "listen";
